name: Push to server (ssh)

on: 
  push:
    branches:
    - main

jobs:
  update-server:
    runs-on: ubuntu-latest
    steps:
    - name: ssh
      run: |
        sudo apt install sshpass -y || apt install sshpass -y
        sshpass -p "${{ secrets.SSH_PASS }}" ssh -tt -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }} 
        cd ~/COP4710-Caregiver || git clone https://github.com/kinneyan/COP4710-Caregiver.git
        git pull
        mv * /var/www/html
      
  