name: Push to server (ssh)

on: 
  push:
    branches:
    - main

jobs:
  update-server:
    runs-on: ubuntu-latest
    steps:
    - name: update-server
      uses: matheusvanzan/sshpass-action@v2
      with:
        host: ${{ secrets.SSH_IP }}
        user: ${{ secrets.SSH_USER }}
        pass: ${{ secrets.SSH_PASSWORD }}
        run: |
          cd ~/COP4710-Caregiver || git clone https://github.com/kinneyan/COP4710-Caregiver.git
          git pull
          rm -r /var/www/html/*
          mv * /var/www/html
      
  